import { createFileRoute } from "@tanstack/react-router";
import { LegalPage } from "@/components/LegalPage";

const d = "Terms of Service for using NetAssist AI, the AI network automation assistant.";
export const Route = createFileRoute("/terms")({
  head: () => ({ meta: [
    { title: "Terms of Service · NetAssist AI" }, { name: "description", content: d },
    { property: "og:title", content: "Terms of Service · NetAssist AI" }, { property: "og:description", content: d },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
  ] }),
  component: () => (
    <LegalPage title="Terms of Service" updated="October 2026" sections={[
      { h: "Acceptance", p: "By creating an account or using NetAssist AI you agree to these terms." },
      { h: "Your account", p: "You are responsible for keeping your credentials secure and for all activity under your account." },
      { h: "AI-generated output", p: "Configurations, scripts, MOPs and other outputs are generated by AI and may contain errors. Always review, validate and test in a lab or approved change window before applying to production networks. You remain responsible for changes made to your infrastructure." },
      { h: "Acceptable use", p: "Do not use the service to attack, scan or access networks you are not authorized to manage, or to abuse, overload or reverse-engineer the platform." },
      { h: "Plans and billing", p: "Free plans include daily usage limits. Paid plans, when available, renew per billing period until cancelled." },
      { h: "Limitation of liability", p: "The service is provided “as is”. To the maximum extent permitted by law, NetAssist AI is not liable for outages, data loss or damages arising from use of generated output." },
      { h: "Changes", p: "We may update these terms; continued use after changes means you accept them." },
    ]} />
  ),
});
